version: '3'
services:
  database:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: electron-ecommerce
      MYSQL_DATABASE: electron_ecommerce
      MYSQL_USER: electron-ecommerce
      MYSQL_PASSWORD: electron-ecommerce
    volumes:
      - db-data:/var/lib/mysql

  server:
    build:
      context: backend/electron-ecommerce-rest/
    ports:
      - 8080:8080
    environment:
      SPRING_DEVTOOLS_REMOTE_SECRET: electron
    depends_on:
      - database
    volumes:
      - ./backend/electron-ecommerce-rest/src:/app/src
      - ./backend/electron-ecommerce-rest/target/classes:/app/target/classes
    command: ["/bin/sh", "-c", "/wait-for-it.sh database:3306 --timeout=15 -- java -Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true -cp /app/classes:/app/resources:/app/dependencies/* org.springframework.boot.loader.Main"]

  #    command: ["/wait-for-it.sh", "database:3306", "--strict", "--timeout=30", "--", "java", "-jar", "app.jar"]

  client:
    build:
      context: frontend/electron-ecommerce-react/
    ports:
      - 5173:5173
    depends_on:
      - server

volumes:
  db-data:

