INSERT INTO electron_ecommerce.reviews (electron_ecommerce.reviews.id,
                                        electron_ecommerce.reviews.rate,
                                        electron_ecommerce.reviews.product_item_id,
                                        electron_ecommerce.reviews.user_id,
                                        electron_ecommerce.reviews.created_on,
                                        electron_ecommerce.reviews.review)
VALUES (1, 4.7,1, 2, CURRENT_DATE,'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (2, 4.3,1, 2, CURRENT_DATE,'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (3, 4.4,1, 2, CURRENT_DATE,'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (4, 4.2,1, 2, CURRENT_DATE,'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (5, 4.1,1, 2, CURRENT_DATE,'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (6, 4.6,1, 2, CURRENT_DATE,'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (7, 4.8,1, 2, CURRENT_DATE,'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (8, 4.3,1, 2, CURRENT_DATE,'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (9, 4.4,1, 2, CURRENT_DATE,'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (10, 4.1,1, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (11, 4.7,2, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (12, 4.3,2, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (13, 4.4,2, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (14, 4.2,2, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (15, 4.1,2, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (16, 4.6,2, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (17, 4.8,2, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (18, 4.3,2, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (19, 4.4,2, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (20, 4.1,2, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (21, 4.7,3, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (22, 4.3,3, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (23, 4.4,3, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (24, 4.2,3, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (25, 4.1,3, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (26, 4.6,3, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (27, 4.8,3, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (28, 4.3,3, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (29, 4.4,3, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (30, 4.1,3, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (31, 4.7,4, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (32, 4.3,4, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (33, 4.4,4, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (34, 4.2,4, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (35, 4.1,4, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (36, 4.6,4, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (37, 4.8,4, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (38, 4.3,4, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (39, 4.4,4, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (40, 4.1,4, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (41, 4.7,5, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (42, 4.3,5, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (43, 4.4,5, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (44, 4.2,5, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (45, 4.1,5, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (46, 4.6,5, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (47, 4.8,5, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (48, 4.3,5, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (49, 4.4,5, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (50, 4.1,5, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (51, 4.7,6, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (52, 4.3,6, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (53, 4.4,6, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (54, 4.2,6, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (55, 4.1,6, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (56, 4.6,6, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (57, 4.8,6, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (58, 4.3,6, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (59, 4.4,6, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (60, 4.1,6, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (61, 4.7,7, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (62, 4.3,7, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (63, 4.4,7, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (64, 4.2,7, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (65, 4.1,7, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (66, 4.6,7, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (67, 4.8,7, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (68, 4.3,7, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (69, 4.4,7, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (70, 4.1,7, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),

       (71, 4.7,8, 2,CURRENT_DATE, 'Ordered RAM from this site and it exceeded expectations! Speedy delivery, effortless install, and my computer''s performance is stellar. Amazing product and service!' ),
       (72, 4.3,8, 2,CURRENT_DATE, 'Snagged some RAM here and it''s incredible! Arrived fast, installed in a snap, and my PC runs like a dream. Superb quality, will buy again!' ),
       (73, 4.4,8, 2,CURRENT_DATE, 'Got my RAM from this site and I''m blown away! Quick to arrive, easy to set up, and my computer is flying. Great value and helpful support.' ),
       (74, 4.2,8, 2,CURRENT_DATE, 'Purchased RAM here and it''s top-notch! Delivery was prompt, installation was a breeze, and my computer''s speed is unbelievable. Excellent service!' ),
       (75, 4.1,8, 2,CURRENT_DATE, 'Bought RAM from this site and I''m super satisfied! Fast shipping, no-fuss installation, and my PC performance is through the roof. Fantastic experience!' ),
       (76, 4.6,8, 2,CURRENT_DATE, 'Acquired RAM from here and it''s a total win! Arrived quickly, super easy to install, and my computer''s responsiveness is amazing. Great product and support!' ),
       (77, 4.8,8, 2,CURRENT_DATE, 'Scored some RAM from this site and it''s perfect! Shipped fast, installation was straightforward, and my PC is now super quick. Very happy with the purchase!' ),
       (78, 4.3,8, 2,CURRENT_DATE, 'Grabbed RAM from this website and it''s impressive! Quick delivery, hassle-free setup, and my computer is much faster. Reliable service, highly recommend!' ),
       (79, 4.4,8, 2,CURRENT_DATE, 'Invested in RAM from this site and it''s worth every penny! Arrived promptly, easy install, and my PC''s performance has skyrocketed. Outstanding quality and support!' ),
       (80, 4.1,8, 2,CURRENT_DATE, 'Chose RAM from this site and it''s a lifesaver! Delivered swiftly, easy to install, and my computer''s speed has improved dramatically. Excellent all around!' ),






       (81, 4.7, 9, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (82, 4.6, 9, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (83, 4.8, 9, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (84, 4.5, 9, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (85, 4.9, 9, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (86, 4.4, 9, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (87, 4.8, 9, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (88, 4.3, 9, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (89, 4.7, 9, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (90, 4.5, 9, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (91, 4.7, 10, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (92, 4.6, 10, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (93, 4.8, 10, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (94, 4.5, 10, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (95, 4.9, 10, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (96, 4.4, 10, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (97, 4.8, 10, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (98, 4.3, 10, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (99, 4.7, 10, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (100, 4.5, 10, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (101, 4.7, 11, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (102, 4.6, 11, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (103, 4.8, 11, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (104, 4.5, 11, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (105, 4.9, 11, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (106, 4.4, 11, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (107, 4.8, 11, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (108, 4.3, 11, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (109, 4.7, 11, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (110, 4.5, 11, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (111, 4.7, 12, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (112, 4.6, 12, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (113, 4.8, 12, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (114, 4.5, 12, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (115, 4.9, 12, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (116, 4.4, 12, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (117, 4.8, 12, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (118, 4.3, 12, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (119, 4.7, 12, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (120, 4.5, 12, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (121, 4.7, 13, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (122, 4.6, 13, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (123, 4.8, 13, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (124, 4.5, 13, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (125, 4.9, 13, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (126, 4.4, 13, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (127, 4.8, 13, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (128, 4.3, 13, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (129, 4.7, 13, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (130, 4.5, 13, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (131, 4.7, 14, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (132, 4.6, 14, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (133, 4.8, 14, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (134, 4.5, 14, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (135, 4.9, 14, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (136, 4.4, 14, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (137, 4.8, 14, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (138, 4.3, 14, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (139, 4.7, 14, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (140, 4.5, 14, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (141, 4.7, 15, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (142, 4.6, 15, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (143, 4.8, 15, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (144, 4.5, 15, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (145, 4.9, 15, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (146, 4.4, 15, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (147, 4.8, 15, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (148, 4.3, 15, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (149, 4.7, 15, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (150, 4.5, 15, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (151, 4.7, 16, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (152, 4.6, 16, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (153, 4.8, 16, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (154, 4.5, 16, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (155, 4.9, 16, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (156, 4.4, 16, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (157, 4.8, 16, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (158, 4.3, 16, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (159, 4.7, 16, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (160, 4.5, 16, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (161, 4.7, 17, 2,CURRENT_DATE, 'The graphics card has transformed my gaming experience with its incredible performance and high frame rates.'),
       (162, 4.6, 17, 2,CURRENT_DATE, 'Stunning visuals and seamless gameplay, thanks to this top-tier graphics card.'),
       (163, 4.8, 17, 2,CURRENT_DATE, 'This card handles 4K gaming like a dream. Worth every penny for serious gamers.'),
       (164, 4.5, 17, 2,CURRENT_DATE, 'Impressed by the cooling efficiency and quiet operation, even under load.'),
       (165, 4.9, 17, 2,CURRENT_DATE, 'Ray tracing technology on this card brings games to life. The future of gaming is here.'),
       (166, 4.4, 17, 2,CURRENT_DATE, 'Exceptional performance boost for creative applications and video editing.'),
       (167, 4.8, 17, 2,CURRENT_DATE, 'Easy to install and configure. Noticed a significant improvement in graphic-intensive tasks.'),
       (168, 4.3, 17, 2,CURRENT_DATE, 'Energy-efficient without compromising on power. Great choice for eco-conscious users.'),
       (169, 4.7, 17, 2, CURRENT_DATE, 'This card''s multi-monitor support is outstanding for multitasking and immersive gaming setups.'),
       (170, 4.5, 17, 2,CURRENT_DATE, 'With this card, my design software runs smoother than ever. Highly recommend for professionals.'),

       (171, 4.6, 18, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (172, 4.7, 18, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (173, 4.5, 18, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (174, 4.8, 18, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (175, 4.4, 18, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (176, 4.6, 18, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (177, 4.9, 18, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (178, 4.5, 18, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (179, 4.7, 18, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (180, 4.8, 18, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (181, 4.6, 19, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (182, 4.7, 19, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (183, 4.5, 19, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (184, 4.8, 19, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (185, 4.4, 19, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (186, 4.6, 19, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (187, 4.9, 19, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (188, 4.5, 19, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (189, 4.7, 19, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (190, 4.8, 19, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (191, 4.6, 20, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (192, 4.7, 20, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (193, 4.5, 20, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (194, 4.8, 20, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (195, 4.4, 20, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (196, 4.6, 20, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (197, 4.9, 20, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (198, 4.5, 20, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (199, 4.7, 20, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (200, 4.8, 20, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (201, 4.6, 21, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (202, 4.7, 21, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (203, 4.5, 21, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (204, 4.8, 21, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (205, 4.4, 21, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (206, 4.6, 21, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (207, 4.9, 21, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (208, 4.5, 21, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (209, 4.7, 21, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (210, 4.8, 21, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (211, 4.6, 22, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (212, 4.7, 22, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (213, 4.5, 22, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (214, 4.8, 22, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (215, 4.4, 22, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (216, 4.6, 22, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (217, 4.9, 22, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (218, 4.5, 22, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (219, 4.7, 22, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (220, 4.8, 22, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (221, 4.6, 23, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (222, 4.7, 23, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (223, 4.5, 23, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (224, 4.8, 23, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (225, 4.4, 23, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (226, 4.6, 23, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (227, 4.9, 23, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (228, 4.5, 23, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (229, 4.7, 23, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (230, 4.8, 23, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (231, 4.6, 24, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (232, 4.7, 24, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (233, 4.5, 24, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (234, 4.8, 24, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (235, 4.4, 24, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (236, 4.6, 24, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (237, 4.9, 24, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (238, 4.5, 24, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (239, 4.7, 24, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (240, 4.8, 24, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (241, 4.6, 25, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (242, 4.7, 25, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (243, 4.5, 25, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (244, 4.8, 25, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (245, 4.4, 25, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (246, 4.6, 25, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (247, 4.9, 25, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (248, 4.5, 25, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (249, 4.7, 25, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (250, 4.8, 25, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),

       (251, 4.6, 26, 2, CURRENT_DATE, 'This keyboard''s tactile feedback is a game-changer for typing. Comfortable and responsive.'),
       (252, 4.7, 26, 2, CURRENT_DATE, 'The RGB lighting adds a fun and customizable aspect to my setup. Keys feel great.'),
       (253, 4.5, 26, 2, CURRENT_DATE, 'Love the build quality and the key layout. Makes for an efficient and enjoyable typing experience.'),
       (254, 4.8, 26, 2, CURRENT_DATE, 'The wireless connectivity is reliable and lag-free. Perfect for a clean desk setup.'),
       (255, 4.4, 26, 2, CURRENT_DATE, 'Impressed by the battery life on this wireless keyboard. Durability meets functionality.'),
       (256, 4.6, 26, 2, CURRENT_DATE, 'The mechanical switches are a delight. Typing for long hours has never been more comfortable.'),
       (257, 4.9, 26, 2, CURRENT_DATE, 'Compact design without sacrificing key functionality. Ideal for limited desk spaces.'),
       (258, 4.5, 26, 2, CURRENT_DATE, 'The customizable hotkeys have streamlined my workflow significantly. Highly intuitive.'),
       (259, 4.7, 26, 2, CURRENT_DATE, 'This keyboard''s quiet keys are a blessing in a shared workspace. Efficiency meets discretion.'),
       (260, 4.8, 26, 2, CURRENT_DATE, 'Ergonomically designed for comfort, reducing strain during long typing sessions. Top-notch.'),




       (181, 4.7, 27, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (182, 4.8, 27, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (183, 4.5, 27, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (184, 4.6, 27, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (185, 4.9, 27, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (186, 4.4, 27, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (187, 4.7, 27, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (188, 4.6, 27, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (189, 4.5, 27, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (190, 4.8, 27, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.'),


       (181, 4.7, 28, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (182, 4.8, 28, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (183, 4.5, 28, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (184, 4.6, 28, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (185, 4.9, 28, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (186, 4.4, 28, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (187, 4.7, 28, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (188, 4.6, 28, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (189, 4.5, 28, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (190, 4.8, 28, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.'),


       (181, 4.7, 29, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (182, 4.8, 29, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (183, 4.5, 29, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (184, 4.6, 29, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (185, 4.9, 29, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (186, 4.4, 29, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (187, 4.7, 29, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (188, 4.6, 29, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (189, 4.5, 29, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (190, 4.8, 29, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.'),


       (191, 4.7, 30, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (192, 4.8, 30, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (193, 4.5, 30, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (194, 4.6, 30, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (195, 4.9, 30, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (196, 4.4, 30, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (197, 4.7, 30, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (198, 4.6, 30, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (199, 4.5, 30, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (200, 4.8, 30, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.'),


       (201, 4.7, 31, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (202, 4.8, 31, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (203, 4.5, 31, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (204, 4.6, 31, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (205, 4.9, 31, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (206, 4.4, 31, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (207, 4.7, 31, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (208, 4.6, 31, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (209, 4.5, 31, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (210, 4.8, 31, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.'),


       (211, 4.7, 32, 2, CURRENT_DATE, 'Absolutely satisfied with this purchase, it exceeded my expectations in every way.'),
       (212, 4.8, 32, 2, CURRENT_DATE, 'Truly outstanding quality, making my viewing experience much more enjoyable.'),
       (213, 4.5, 32, 2, CURRENT_DATE, 'Very happy with this monitor, it has been a fantastic addition to my setup.'),
       (214, 4.6, 32, 2, CURRENT_DATE, 'Impressed with the overall performance, it has certainly met all my needs.'),
       (215, 4.9, 32, 2, CURRENT_DATE, 'Delighted with this product, it''s been a game-changer for my daily tasks.'),
       (216, 4.4, 32, 2, CURRENT_DATE, 'Very pleased with this monitor, it offers great value and quality.'),
       (217, 4.7, 32, 2, CURRENT_DATE, 'This monitor has been an excellent choice, highly satisfied with its performance.'),
       (218, 4.6, 32, 2, CURRENT_DATE, 'A fantastic monitor that has lived up to all my expectations, highly recommend it.'),
       (219, 4.5, 32, 2, CURRENT_DATE, 'This monitor has significantly enhanced my experience, very glad I chose it.'),
       (220, 4.8, 32, 2, CURRENT_DATE, 'Extremely happy with this monitor, it''s been perfect for both work and play.');








