import {Bold} from "../reusable/Bold.tsx";
import {ParagraphSmall} from "../reusable/ParagraphSmall.tsx";
import {ElectronButton} from "../reusable/ElectronButton.tsx";
import React from "react";
import {useNavigate} from "react-router-dom";
import {SEARCH_ROUTE} from "../../constants/Routes.ts";
import {useViewport} from "../../custom_hooks/useViewport.ts";
import {Breakpoints} from "../../constants/Breakpoints.ts";
import {RevealAnimation} from "../reusable/RevealAnimation.tsx";

export type CategoryHeroProps = {
    imgSrc: string,
    imgLeft: boolean,
    category: string,
    header: string,
    headerDescription: string,
    children: React.ReactNode,

}

export const CategoryHero = ({imgSrc, imgLeft, category, header, headerDescription, children}: CategoryHeroProps) => {

    const navigate = useNavigate();
    const viewPort = useViewport();

    const handleClick = () => {
        navigate(SEARCH_ROUTE + "/" + category);
    }

    if (viewPort <= Breakpoints.SMALL) return (
        <div>
            <RevealAnimation>
                <div
                    className="flex flex-col sm:flex-row gap-5 border-l sm:border-l-0  border-r sm:border-t border-b border-electron-input-grey rounded-lg">
                    <div className="w-full sm:w-1/2">
                        <img className="rounded-t-lg sm:rounded-r-none sm:rounded-l-lg "
                             src={imgSrc}
                             alt="computer part img generated by ai"/>
                    </div>
                    <div className="w-full sm:w-1/2 px-3 py-5 flex flex-col items-center text-center">
                        <Bold textSize={18} weight={600}>{header}</Bold>
                        <div className="flex flex-col gap-5 h-full">

                            <ParagraphSmall>{headerDescription}</ParagraphSmall>
                            <ParagraphSmall>{children}</ParagraphSmall>
                            <div className="mt-auto"
                                 onClick={handleClick}>
                                <ElectronButton>Explore</ElectronButton>
                            </div>
                        </div>
                    </div>
                </div>
            </RevealAnimation>
        </div>
    )


    return (
        <>
            <RevealAnimation>

                {
                    imgLeft ?
                        <div
                            className="flex flex-col sm:flex-row gap-5 border-l sm:border-l-0  border-r sm:border-t border-b border-electron-input-grey rounded-lg">
                            <div className="w-full sm:w-1/2">
                                <img className="rounded-t-lg sm:rounded-r-none sm:rounded-l-lg "
                                     src={imgSrc}
                                     alt="computer part img generated by ai"/>
                            </div>
                            <div className="w-full sm:w-1/2 px-3 py-5 flex flex-col items-center text-center">
                                <Bold textSize={18} weight={600}>{header}</Bold>
                                <div className="flex flex-col gap-5 h-full">

                                    <ParagraphSmall>{headerDescription}</ParagraphSmall>
                                    <ParagraphSmall>{children}</ParagraphSmall>
                                    <div className="mt-auto"
                                         onClick={handleClick}>
                                        <ElectronButton>Explore</ElectronButton>
                                    </div>
                                </div>
                            </div>
                        </div>
                        :
                        <div
                            className="flex flex-col sm:flex-row gap-5 sm:border-l sm:border-t border-b border-electron-input-grey rounded-lg">
                            <div className="w-full sm:w-1/2 px-3 py-5 flex flex-col items-center text-center">
                                <Bold textSize={18} weight={600}>{header}</Bold>
                                <div className="flex flex-col gap-5 h-full">

                                    <ParagraphSmall>{headerDescription}</ParagraphSmall>
                                    <ParagraphSmall>{children}</ParagraphSmall>
                                    <div className="mt-auto"
                                         onClick={handleClick}>
                                        <ElectronButton>Explore</ElectronButton>
                                    </div>
                                </div>
                            </div>
                            <div className="w-full sm:w-1/2">
                                <img className="rounded-t-lg sm:rounded-l-none sm:rounded-r-lg "
                                     src={imgSrc}
                                     alt="computer part img generated by ai"/>
                            </div>

                        </div>
                }
            </RevealAnimation>

        </>
    )
}
