import {Swiper, SwiperSlide} from "swiper/react";
import {Autoplay, Pagination} from "swiper/modules";

export const Hero = () => {

    const images = ['https://electron-img-01.s3.eu-west-2.amazonaws.com/extpc2.jpg',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/extpc1.jpg',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/extkeyboard.jpg']


    return (
        <div className="rounded-lg overflow-hidden">
            <Swiper className="mySwiper"
                    pagination={{clickable: true}}
                    modules={[Pagination, Autoplay]}
                    autoplay={{
                        delay: 10000,
                        disableOnInteraction: true
                    }}
            >

                {images.map((image, key) => (
                    <SwiperSlide key={key}>
                        <div className="relative">
                            <img className="" alt="computer component generated by ai" src={image}/>
                            <p className="absolute text-electron-primary-white top-[25%] left-[12%]">
                                Build your dream pc today
                            </p>
                        </div>
                    </SwiperSlide>
                ))}
                <div className="swiper-pagination-bullet-active"></div>


            </Swiper>

        </div>
    )
}