import {Swiper, SwiperSlide} from "swiper/react";
import {Autoplay, Pagination} from "swiper/modules";
import {useViewport} from "../../custom_hooks/useViewport.ts";
import {useEffect, useState} from "react";
import {Breakpoints} from "../../constants/Breakpoints.ts";

export const Hero = () => {

    const images = ['https://electron-img-01.s3.eu-west-2.amazonaws.com/extpc2.jpg',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/extpc1.jpg',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/extkeyboard.jpg']

    const mobileImages = ['https://electron-img-01.s3.eu-west-2.amazonaws.com/keyboardMob.webp',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/keymobile.webp',
        'https://electron-img-01.s3.eu-west-2.amazonaws.com/memorymobile.webp']

    const [img, setImg] = useState<string[]>([]);

    const viewport = useViewport();

    useEffect(() => {
        if (viewport >= Breakpoints.SMALL) {
            setImg(images);
        } else {
            setImg(mobileImages);
        }
    }, [viewport]);


    return (
        <div className="w-full max-w-[1440px]">
            <Swiper className="mySwiper"
                    pagination={{clickable: true}}
                    modules={[Pagination, Autoplay]}
                    autoplay={{
                        delay: 10000,
                        disableOnInteraction: true
                    }}
            >

                {img.map((image, key) => (
                    <SwiperSlide key={key}>
                        <div className="relative">
                            <img className="" alt="computer component generated by ai" src={image}/>
                            <p className="absolute text-electron-primary-white top-[25%] left-[12%]">
                                Build your dream pc today
                            </p>
                        </div>
                    </SwiperSlide>
                ))}
                <div className="swiper-pagination-bullet-active"></div>


            </Swiper>

        </div>
    )
}