name: CD

on:
  workflow_run: 
    workflows: [ "CI" ]
    types:
      - completed
    
jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: |
          cd /home/ubuntu/apps/electron/
          docker compose down
          docker rm undermad/electron || true
          docker rm undermad/electron-front || true
          docker rmi undermad/electron || true
          docker rmi undermad/electron-front || true
          docker compose up -d
      
      

  
  